import Head from "next/head";
import Link from "next/link";
import React from "react";
import { useContext } from "react";
import { Store } from "../utils/Store";
import { useState } from "react";
import { useEffect } from "react";
import { ToastContainer } from "react-toastify";
import { Menu } from "@headlessui/react";
import { signOut, useSession } from "next-auth/react";
import 'react-toastify/dist/ReactToastify.css'
import DropdownLink from "./DropdownLink";
import Cookies from "js-cookie";
import { useRouter } from "next/router";
import {MagnifyingGlassIcon} from "@heroicons/react/24/solid"

export function Layout({ title, children }) {
  const { status, data: session } = useSession();

  const { state, dispatch } = useContext(Store);
  const { cart } = state;
  const [cartItemsCount, setCartItemsCount] = useState(0);
  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  const logoutClickHandler = () => {
    Cookies.remove('cart')

    dispatch({ type: 'CART_RESET' })
    signOut({ callbackUrl: '/login'})
  }

  const [query, setQuery] = useState('')

  const router = useRouter()
  const submitHandler = (e) => {
    e.preventDefault()
    router.push(`/search?query=${query}`)
  }
  return (
    <>
      <Head>
        <title>{title ? title + " - uVinyl" : "uVinyl"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="Ecommerce Website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="bottom-center" limit={1} />
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex h-12 justify-between shadow-md it ems-center px-4">
            <Link href="/" className="pt-1">
              <img src="/images/Logow.png" width={100} height={40}/>
            </Link>
            <form
            onSubmit={submitHandler}
            className='mx-auto hidden justify-center md:flex'>
              <input
              onChange={(e) => setQuery(e.target.value)}
              type='text'
              className="rounded-tr-none rounded-br-none p-1 text-sm focus:ring-0"
              placeholder="Search vinyl"/>
            <button
            className="rounded rounded-tl-none rounded-bl-none bg-amber-300 p-1 text-sm dark:text-black"
            type='submit'
            id='button-addon2'
            >
              <MagnifyingGlassIcon className='h-5 w-5'></MagnifyingGlassIcon>
            </button>
            </form>
            <div>
              <Link href="/cart" className="p-2 text-[18px]">
                Cart
                {cartItemsCount > 0 && (
                  <span className="ml-2 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cartItemsCount}
                  </span>
                )}
              </Link>

              {status === "loading" ? (
                "Loading"
              ) : session?.user ? (
                <Menu as='div' className={'relative inline-block'}>
                    <Menu.Button className='text-[#6792C4] text-[18px] p-2'>
                        {session.user.name}
                    </Menu.Button>
                    <Menu.Items className='absolute right-0 w-56 origin-top-right bg-white shadow-lg'>
                        <Menu.Item>
                            <DropdownLink className='dropdown-link' href='/profile'>
                                Profile
                            </DropdownLink>
                        </Menu.Item>
                        <DropdownLink className='dropdown-link' href='/order-history'>
                            Order History
                        </DropdownLink>
                        <a className="dropdown-link" href="#" onClick={logoutClickHandler}>
                            Logout
                        </a>
                    </Menu.Items>
                </Menu>
              ) : (
                <Link href="/login" className="p-2 text-[20px]">
                  Login
                </Link>
              )}
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex justify-center items-center h-10 shadow-inner">
          <p>Copyright 2023 uVinyl</p>
        </footer>
      </div>
    </>
  );
}
